# --join MEANS TO COMBINE
# JOIN CLAUSE COMBINES DATA FROM 2 OR MORE TABLES ,BASED ON A RELATED COLUMN BETWEEN THEM
# EXAMPLE


# CUSTOMER         PAYMENT
#  |                   |
#  |     			         |
#  V				           V
#  CUST_ID -------> CUST_ID
#  FIRST_NAME       AMOUNT
#  LAST_NAME        MODE
#  ADDRESS_ID       PAYMENT_ID
 
 
#  ADDRESS		 COUNTRY
#  ADD_ID             CITY_ID
#  ADDRESS           CITY
#  CITY_ID           COUNTRY
#  POSTAL_CODE
#  PHONE         
